# Centralized version configuration for FalkorDBLite
# This file defines the versions of Redis and FalkorDB used across CI/CD and build processes

redis_version: '8.2.2'
falkordb_version: 'v4.14.7'

# Legacy Redis version for specific build configurations
redis_version_legacy: '6.2.14'
