# Codecov configuration
codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        # Low threshold to avoid breaking existing CI
        # Adjust upward once baseline coverage is established
        threshold: 0.5%
        if_ci_failed: error

    patch:
      default:
        target: auto
        # Low threshold initially to not block existing PRs
        # Consider increasing to 50-80% for new code coverage
        threshold: 0.5%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

flags:
  unittests:
    paths:
      - redislite/
  unittests-macos:
    paths:
      - redislite/

ignore:
  - "tests/**/*"
  - "examples/**/*"
  - "docs/**/*"
  - "build_scripts/**/*"
  - "setup.py"
  - "verify_install.py"
